In [32]:
  
import numpy as np
from numpy.linalg import inv
from numpy import linalg as LA

M = np.array([[1,0],[0,1],[1/2,1]])
P = np.array([[0],[1],[-1]])
MM_T=np.dot(M,M.T)
M_TM=np.dot(M.T,M)
print('MM_T')
print(MM_T)
print('M_TM')
print(M_TM)
#Eigenvalues and eigenvectors
D_vec1,P1 = np.linalg.eig(MM_T)
D_vec2,P2 = np.linalg.eig(M_TM)
print('eigen value for MM_T')
print(D_vec1)
print('normalized eigen vector for MM_T')
print(P1)
print('eigen value for M_TM')
print(D_vec2)
print('normalized eigen vector for M_TM')
print(P2)
#Singular Value Decomposition
U, s, V=LA.svd(M)

S = np.zeros(M.shape)
Sinv = S.T
S[:2,:2] = np.diag(s)
sinv = 1./s

#Moore Penrose Pseudo Inverse
Sinv[:2,:2] = np.diag(sinv)

#Solution
x = V.T.dot(Sinv).dot(U.T).dot(P)
print('coordinates of the foot of the perpendicular')
print(x)
Q=np.array([[-0.444],[ 0.111],[0]])
PQ=np.linalg.norm(P-Q)
print('distance between the point of intersection of lines and plane:',(PQ))

MM_T
[[1.   0.   0.5 ]
 [0.   1.   1.  ]
 [0.5  1.   1.25]]
M_TM
[[1.25 0.5 ]
 [0.5  2.  ]]
eigen value for MM_T
[2.25000000e+00 1.00000000e+00 8.85768348e-17]
normalized eigen vector for MM_T
[[-2.98142397e-01 -8.94427191e-01 -3.33333333e-01]
 [-5.96284794e-01  4.47213595e-01 -6.66666667e-01]
 [-7.45355992e-01 -2.70547446e-16  6.66666667e-01]]
eigen value for M_TM
[1.   2.25]
normalized eigen vector for M_TM
[[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]
coordinates of the foot of the perpendicular
[[-0.44444444]
 [ 0.11111111]]
distance between the point of intersection of lines and plane: 1.4097719673762845
