In [13]:
import numpy as np
import math
import matplotlib.pyplot as plt
from numpy import linalg as LA
from numpy.linalg import matrix_rank
#Input parameters
x = np.array([[1,1,1,1,1],
             [1,2,2,2,2],
             [1,2,3,3,3],
             [1,2,3,4,4],
             [1,2,3,4,5]]) 
print((x))
r=np.linalg.matrix_rank(x)
print('rank of the matrix',(r))

[[1 1 1 1 1]
 [1 2 2 2 2]
 [1 2 3 3 3]
 [1 2 3 4 4]
 [1 2 3 4 5]]
rank of the matrix 5
